<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.anominy</groupId>
    <artifactId>uwutils</artifactId>
    <version>0.3-r1</version>

    <packaging>pom</packaging>

    <modules>
        <module>uwutils-object</module>
        <module>uwutils-interface</module>
        <module>uwutils-collection</module>
        <module>uwutils-list</module>
        <module>uwutils-set</module>
        <module>uwutils-map</module>
        <module>uwutils-array</module>
        <module>uwutils-string</module>
    </modules>

    <name>${project.groupId}:${project.artifactId}</name>
    <description>Safe &amp; exception-free library for common utilities w/ Java 8+ support</description>
    <url>https://github.com/anominy/uwutils</url>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>anominy</id>
            <url>https://github.com/anominy</url>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/anominy/uwutils.git</connection>
        <developerConnection>scm:git:ssh://github.com:anominy/uwutils.git</developerConnection>
        <url>https://github.com/anominy/uwutils/tree/0.3-dev</url>
    </scm>

    <distributionManagement>
        <snapshotRepository>
            <id>ossrh</id>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>ossrh</id>
            <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2</url>
        </repository>
    </distributionManagement>

    <properties>
        <!-- Java Version -->
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>

        <!-- Project Encoding -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <uwutils-object.version>0.3-r1</uwutils-object.version>
        <uwutils-interface.version>0.3-r1</uwutils-interface.version>
        <uwutils-collection.version>0.3-r1</uwutils-collection.version>
        <uwutils-list.version>0.3-r1</uwutils-list.version>
        <uwutils-set.version>0.3-r1</uwutils-set.version>
        <uwutils-map.version>0.3-r1</uwutils-map.version>
        <uwutils-array.version>0.3-r1</uwutils-array.version>
        <uwutils-string.version>0.3-r1</uwutils-string.version>
        <jetbrains-annotations.version>24.1.0</jetbrains-annotations.version>

        <!-- Maven Plugin Versions -->
        <maven.install.version>2.5.2</maven.install.version>
        <maven.source.version>3.2.1</maven.source.version>
        <maven.javadoc.version>3.4.1</maven.javadoc.version>
        <maven.gpg.version>3.0.1</maven.gpg.version>
        <maven.staging.version>1.6.13</maven.staging.version>
        <maven.central.version>0.6.0</maven.central.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.anominy</groupId>
                <artifactId>uwutils-object</artifactId>
                <version>${uwutils-object.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.anominy</groupId>
                <artifactId>uwutils-interface</artifactId>
                <version>${uwutils-interface.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.anominy</groupId>
                <artifactId>uwutils-collection</artifactId>
                <version>${uwutils-collection.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.anominy</groupId>
                <artifactId>uwutils-list</artifactId>
                <version>${uwutils-list.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.anominy</groupId>
                <artifactId>uwutils-set</artifactId>
                <version>${uwutils-set.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.anominy</groupId>
                <artifactId>uwutils-map</artifactId>
                <version>${uwutils-map.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.anominy</groupId>
                <artifactId>uwutils-array</artifactId>
                <version>${uwutils-array.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.anominy</groupId>
                <artifactId>uwutils-string</artifactId>
                <version>${uwutils-string.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>annotations</artifactId>
                <version>${jetbrains-annotations.version}</version>
                <optional>true</optional>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>${maven.install.version}</version>
                <configuration>
                    <createChecksum>false</createChecksum>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>build</id>
            <activation>
                <activeByDefault>false</activeByDefault>
                <property>
                    <name>ossrh</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>${maven.source.version}</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>javadoc</id>
            <activation>
                <activeByDefault>false</activeByDefault>
                <property>
                    <name>ossrh</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>${maven.javadoc.version}</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>release</id>
            <activation>
                <activeByDefault>false</activeByDefault>
                <property>
                    <name>ossrh</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-install-plugin</artifactId>
                        <version>${maven.install.version}</version>
                        <configuration>
                            <createChecksum>true</createChecksum>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${maven.gpg.version}</version>
                        <configuration>
                            <keyname>C0E302B259637BCE</keyname>
                            <passphraseServerId>C0E302B259637BCE</passphraseServerId>
                        </configuration>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>${maven.central.version}</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
